#!/bin/sh

set -e

PREREQ="cryptroot"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/ykchalresp
copy_exec /usr/bin/ykinfo
copy_exec /usr/bin/awk
copy_exec /usr/bin/sha256sum
cp /usr/share/yubikey-luks-1fa/ykluks-1fa-keyscript "${DESTDIR}/sbin/ykluks-1fa-keyscript"

exit 0
