#! /bin/sh
#
# This is /sbin/ykluks-keyscript, which gets called when unlocking the disk
#

message()
{
    if [ -x /bin/plymouth ] && plymouth --ping; then
        plymouth message --text="$*"
    else
        echo "$@" >&2
    fi
    return 0
}

# source for log_*_msg() functions, see LP: #272301
if [ -e /scripts/functions ] ; then
	. /scripts/functions
else
	. /usr/share/initramfs-tools/scripts/functions
fi

challenge="$1"
if ykinfo -q -2 1>/dev/null 2>/dev/null; then
  yubikey_present="1"
else
  yubikey_present="0"
fi

message "Attempt to unlock disk $cryptsource ($crypttarget)"

if [ "$yubikey_present" = "1" -a -n "$challenge" ]; then
  message "Using yubikey to generate passphrase..."
  response="$(ykchalresp -2 "$challenge" 2>/dev/null | sha256sum | awk '{print $1}')"
	message "Retrieved the response from the Yubikey"

  printf '%s' "$response"
else
  if [ -z "$cryptkeyscript" ]; then
    if [ -x /bin/plymouth ] && plymouth --ping; then
          cryptkeyscript="plymouth ask-for-password --prompt"
      else
          cryptkeyscript="/lib/cryptsetup/askpass"
      fi
  fi

  PW="$($cryptkeyscript "Please enter passphrase:")"

	printf '%s' "$PW"
fi

exit 0
